#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
clean-onset-outputs.py
----------------------

Safely clean outputs generated by the new PCHIP/IA/FBRM onset workflow.

This script is deliberately narrow in scope. It is NOT a generic analysis
cleanup tool and it must not remove measurement data, aligned input data,
preprocessing outputs, SSR audit outputs, logs, progress files, or manually
created files.

Default mode is --dry-run: nothing is changed.

2026-06-18 fix 1: protected-path matching is structural, so generated
analysis/pchip/*.log files no longer prevent pchip/ from being archived.
2026-06-18 fix 2: restore now works also from a copied archive directory;
the restore source is resolved primarily as <selected archive>/<original_path>.

Typical use
-----------

cd $PROJECT_ROOT

# Show what would be archived/removed.
python scripts/clean-onset-outputs.py --dry-run

# Safest real cleanup: move generated workflow outputs under project root.
python scripts/clean-onset-outputs.py --archive

# Destructive cleanup, only for exceptional cases.
python scripts/clean-onset-outputs.py --delete --confirm-delete-new-workflow-outputs

# Restore an archive created by --archive. By default, existing targets are
# not overwritten; only missing targets are restored.
python scripts/clean-onset-outputs.py --restore _cleanup_archive/cleanup-YYYYMMDD_HHMMSS

# Preview restore without modifying anything.
python scripts/clean-onset-outputs.py --restore _cleanup_archive/cleanup-YYYYMMDD_HHMMSS --restore-dry-run

Scope
-----

The normal cleanup whitelist is limited to output directories generated by the
new onset/PCHIP/FBRM workflow:

  */tl/roi/rgb/analysis/pchip/
  */tl/roi/rgb/analysis/fbrm_onsets/
  */tl/roi/rgb/analysis/combo/
  galleries/

The script intentionally does NOT clean root-level legacy-looking directories
such as:

  */analysis/
  */fbrm_onsets/

Those may contain legacy results or other material and are outside this scope.

Fundamental files/directories explicitly outside this script's scope:

  */tl/roi/rgb/analysis/rgb-tr.csv
  */tl/roi/rgb/analysis/ts-fbrm-tr.csv
  */tl/roi/rgb/analysis/merged_rgb_counts.csv
  */tl/roi/rgb/analysis/ssr/
  */tl/roi/rgb/analysis/ssr-tr/
  */tl/roi/rgb/analysis/*.log
  */tl/roi/rgb/rgb.csv
  */ts-fbrm.csv
  */ts-fbrm-tr.csv
  */processing.log
  */progress.txt

If those files are ever cleaned, that must be done by a separate preprocessing
or raw-data cleanup script, not by this onset-output cleanup script.
"""

from __future__ import annotations

import argparse
import csv
import os
import shutil
import sys
from dataclasses import dataclass
from datetime import datetime
from pathlib import Path
from typing import Iterable, Sequence


SCRIPT_NAME = "clean-onset-outputs.py"
DEFAULT_ARCHIVE_DIRNAME = "_cleanup_archive"

# Strong allowlist: these are the only normal cleanup targets.
WORKFLOW_DIR_TARGETS = {
    "pchip": Path("tl/roi/rgb/analysis/pchip"),
    "fbrm_onsets": Path("tl/roi/rgb/analysis/fbrm_onsets"),
    "combo": Path("tl/roi/rgb/analysis/combo"),
}

PROJECT_ROOT_TARGETS = {
    "galleries": Path("galleries"),
}

# Denylist: these are not cleanup targets for this script.
#
# Important implementation note:
# Do NOT use shell-style fnmatch patterns such as
# "*/tl/roi/rgb/analysis/*.log" for this check, because Python fnmatch treats
# "/" as an ordinary character. That would also match files below
# analysis/pchip/, for example:
#
#   20990101_ex_99/tl/roi/rgb/analysis/pchip/bw-pchip-workflow.log
#
# Such files are generated workflow outputs and are safe cleanup targets.
# Therefore the protected-path logic below is structural and only protects
# exact/direct fundamental measurement, alignment, preprocessing and log paths.
ANALYSIS_ROOT_PROTECTED_FILES = {
    "rgb-tr.csv",
    "ts-fbrm-tr.csv",
    "merged_rgb_counts.csv",
}

ANALYSIS_ROOT_PROTECTED_DIRS = {
    "ssr",
    "ssr-tr",
}

EXPERIMENT_ROOT_PROTECTED_FILES = {
    "ts-fbrm.csv",
    "ts-fbrm-tr.csv",
    "processing.log",
    "progress.txt",
}


@dataclass(frozen=True)
class Candidate:
    kind: str
    path: Path
    relpath: Path
    file_count: int
    dir_count: int
    total_bytes: int
    reason: str


def parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser(
        description=(
            "Dry-run, archive, or delete only the new PCHIP/IA/FBRM onset "
            "workflow output directories. The default is --dry-run."
        ),
        formatter_class=argparse.ArgumentDefaultsHelpFormatter,
    )

    parser.add_argument(
        "--project-root",
        type=Path,
        default=Path.cwd(),
        help="Project root. Default is the current working directory.",
    )

    mode = parser.add_mutually_exclusive_group()
    mode.add_argument(
        "--dry-run",
        action="store_true",
        help="Only list cleanup candidates; do not modify anything.",
    )
    mode.add_argument(
        "--archive",
        action="store_true",
        help=(
            "Move cleanup candidates under <project-root>/_cleanup_archive/"
            "cleanup-<timestamp>/ and write a manifest."
        ),
    )
    mode.add_argument(
        "--delete",
        action="store_true",
        help="Permanently delete cleanup candidates. Requires confirmation flag.",
    )
    mode.add_argument(
        "--restore",
        type=Path,
        metavar="ARCHIVE_DIR",
        help=(
            "Restore an archive created by --archive. Existing targets are skipped "
            "by default unless --restore-overwrite is also given."
        ),
    )

    parser.add_argument(
        "--confirm-delete-new-workflow-outputs",
        action="store_true",
        help="Required with --delete to confirm destructive cleanup.",
    )
    parser.add_argument(
        "--archive-root",
        type=Path,
        default=None,
        help=(
            "Archive root directory. Relative paths are resolved under the "
            "project root. Default: _cleanup_archive."
        ),
    )
    parser.add_argument(
        "--restore-dry-run",
        action="store_true",
        help="Preview --restore actions without moving anything.",
    )
    parser.add_argument(
        "--restore-overwrite",
        action="store_true",
        help=(
            "Allow --restore to replace existing target directories. Requires "
            "--confirm-restore-overwrite."
        ),
    )
    parser.add_argument(
        "--confirm-restore-overwrite",
        action="store_true",
        help="Required with --restore-overwrite.",
    )
    parser.add_argument(
        "--only",
        nargs="+",
        choices=sorted(set(WORKFLOW_DIR_TARGETS) | set(PROJECT_ROOT_TARGETS)),
        default=None,
        help=(
            "Limit cleanup to selected output kinds. Choices: pchip, "
            "fbrm_onsets, combo, galleries."
        ),
    )
    parser.add_argument(
        "--experiments",
        nargs="+",
        default=None,
        help=(
            "Limit cleanup to specific experiment directory names, for example "
            "20990101_ex_99 20990101_ex_99. Does not affect project-root galleries."
        ),
    )
    parser.add_argument(
        "--include-galleries",
        action=argparse.BooleanOptionalAction,
        default=True,
        help="Include project-root galleries/ as a cleanup target.",
    )
    parser.add_argument(
        "--require-marker",
        action="store_true",
        help=(
            "Clean only directories containing .generated-by-onset-workflow.json. "
            "Useful later after the runner writes marker files. Existing legacy "
            "outputs may not have this marker."
        ),
    )
    parser.add_argument(
        "--allow-untrusted-root",
        action="store_true",
        help=(
            "Bypass project-root sanity checks. Use only if the project root "
            "does not have the normal PCHIP snapshot structure."
        ),
    )
    parser.add_argument(
        "--verbose",
        action="store_true",
        help="Print skipped candidates and extra diagnostics.",
    )

    args = parser.parse_args()

    if not (args.dry_run or args.archive or args.delete or args.restore):
        args.dry_run = True

    if args.delete and not args.confirm_delete_new_workflow_outputs:
        parser.error("--delete requires --confirm-delete-new-workflow-outputs")

    if args.restore_dry_run and not args.restore:
        parser.error("--restore-dry-run requires --restore ARCHIVE_DIR")

    if args.restore_overwrite and not args.restore:
        parser.error("--restore-overwrite requires --restore ARCHIVE_DIR")

    if args.restore_overwrite and not args.confirm_restore_overwrite:
        parser.error("--restore-overwrite requires --confirm-restore-overwrite")

    return args


def rel_posix(path: Path, root: Path) -> str:
    return path.relative_to(root).as_posix()


def is_never_touch_path(path: Path, root: Path) -> bool:
    """Return True if the path itself is a protected fundamental path.

    This matcher is intentionally structural. In particular, analysis/*.log
    means only direct log files in the analysis root, not logs inside generated
    workflow output directories such as analysis/pchip/.
    """
    try:
        rel = path.relative_to(root)
    except ValueError:
        return True

    parts = rel.parts

    # Experiment-root protected files:
    #   <experiment>/ts-fbrm.csv
    #   <experiment>/ts-fbrm-tr.csv
    #   <experiment>/processing.log
    #   <experiment>/progress.txt
    if len(parts) == 2 and parts[1] in EXPERIMENT_ROOT_PROTECTED_FILES:
        return True

    # ROI RGB root protected file:
    #   <experiment>/tl/roi/rgb/rgb.csv
    if len(parts) == 5 and parts[1:4] == ("tl", "roi", "rgb") and parts[4] == "rgb.csv":
        return True

    # Analysis-root protected files and directories:
    #   <experiment>/tl/roi/rgb/analysis/rgb-tr.csv
    #   <experiment>/tl/roi/rgb/analysis/ts-fbrm-tr.csv
    #   <experiment>/tl/roi/rgb/analysis/merged_rgb_counts.csv
    #   <experiment>/tl/roi/rgb/analysis/*.log       (direct children only)
    #   <experiment>/tl/roi/rgb/analysis/ssr[/...]
    #   <experiment>/tl/roi/rgb/analysis/ssr-tr[/...]
    if len(parts) >= 6 and parts[1:5] == ("tl", "roi", "rgb", "analysis"):
        tail = parts[5:]

        if len(tail) == 1 and tail[0] in ANALYSIS_ROOT_PROTECTED_FILES:
            return True

        if len(tail) == 1 and tail[0].endswith(".log"):
            return True

        if len(tail) >= 1 and tail[0] in ANALYSIS_ROOT_PROTECTED_DIRS:
            return True

    return False


def contains_never_touch_path(path: Path, root: Path) -> bool:
    """Return True if path or any child matches the hard denylist."""
    if is_never_touch_path(path, root):
        return True
    if not path.is_dir():
        return False
    for child in path.rglob("*"):
        if is_never_touch_path(child, root):
            return True
    return False


def directory_stats(path: Path) -> tuple[int, int, int]:
    """Return (file_count, dir_count, total_bytes) without following symlinks."""
    file_count = 0
    dir_count = 0
    total_bytes = 0

    if path.is_file() and not path.is_symlink():
        return 1, 0, path.stat().st_size

    for child in path.rglob("*"):
        if child.is_symlink():
            continue
        if child.is_file():
            file_count += 1
            try:
                total_bytes += child.stat().st_size
            except OSError:
                pass
        elif child.is_dir():
            dir_count += 1

    return file_count, dir_count, total_bytes


def looks_like_project_root(root: Path) -> bool:
    """Basic sanity check to avoid running from an accidental wrong directory."""
    if not (root / "scripts").is_dir():
        return False

    experiment_dirs = [
        p for p in root.iterdir()
        if p.is_dir()
        and not p.is_symlink()
        and "_ex_" in p.name
    ]
    return bool(experiment_dirs)


def iter_experiment_dirs(root: Path, experiments: Sequence[str] | None) -> Iterable[Path]:
    wanted = set(experiments or [])
    for path in sorted(root.iterdir()):
        if not path.is_dir() or path.is_symlink():
            continue
        if "_ex_" not in path.name:
            continue
        if wanted and path.name not in wanted:
            continue
        yield path


def target_kind_enabled(kind: str, only: Sequence[str] | None) -> bool:
    return only is None or kind in set(only)


def collect_candidates(
    root: Path,
    *,
    only: Sequence[str] | None,
    experiments: Sequence[str] | None,
    include_galleries: bool,
    require_marker: bool,
    verbose: bool,
) -> list[Candidate]:
    candidates: list[Candidate] = []

    for exp_dir in iter_experiment_dirs(root, experiments):
        for kind, rel_target in WORKFLOW_DIR_TARGETS.items():
            if not target_kind_enabled(kind, only):
                continue

            target = exp_dir / rel_target
            if not target.exists():
                continue

            maybe_add_candidate(
                candidates,
                root=root,
                path=target,
                kind=kind,
                require_marker=require_marker,
                reason=f"workflow output: {rel_target.as_posix()}",
                verbose=verbose,
            )

    if include_galleries and target_kind_enabled("galleries", only):
        gallery_target = root / PROJECT_ROOT_TARGETS["galleries"]
        if gallery_target.exists():
            maybe_add_candidate(
                candidates,
                root=root,
                path=gallery_target,
                kind="galleries",
                require_marker=False,
                reason="project-root gallery output",
                verbose=verbose,
            )

    return candidates


def maybe_add_candidate(
    candidates: list[Candidate],
    *,
    root: Path,
    path: Path,
    kind: str,
    require_marker: bool,
    reason: str,
    verbose: bool,
) -> None:
    """Validate and append a cleanup candidate."""
    path = path.resolve()
    root = root.resolve()

    try:
        relpath = path.relative_to(root)
    except ValueError:
        print(f"[skip] outside project root: {path}", file=sys.stderr)
        return

    if path.is_symlink():
        print(f"[skip] symlink target is never cleaned: {relpath}", file=sys.stderr)
        return

    if not path.is_dir():
        print(f"[skip] target is not a directory: {relpath}", file=sys.stderr)
        return

    if contains_never_touch_path(path, root):
        print(
            f"[skip] target contains a protected measurement/alignment path: {relpath}",
            file=sys.stderr,
        )
        return

    if require_marker and not (path / ".generated-by-onset-workflow.json").is_file():
        if verbose:
            print(f"[skip] missing workflow marker: {relpath}", file=sys.stderr)
        return

    file_count, dir_count, total_bytes = directory_stats(path)
    candidates.append(
        Candidate(
            kind=kind,
            path=path,
            relpath=relpath,
            file_count=file_count,
            dir_count=dir_count,
            total_bytes=total_bytes,
            reason=reason,
        )
    )


def format_bytes(num_bytes: int) -> str:
    units = ["B", "KiB", "MiB", "GiB", "TiB"]
    value = float(num_bytes)
    for unit in units:
        if abs(value) < 1024.0 or unit == units[-1]:
            return f"{value:.1f} {unit}"
        value /= 1024.0
    return f"{num_bytes} B"


def resolve_archive_root(project_root: Path, archive_root: Path | None) -> Path:
    if archive_root is None:
        return project_root / DEFAULT_ARCHIVE_DIRNAME
    if archive_root.is_absolute():
        return archive_root
    return project_root / archive_root


def write_manifest(
    manifest_csv: Path,
    manifest_txt: Path,
    *,
    project_root: Path,
    mode: str,
    candidates: Sequence[Candidate],
    actions: Sequence[tuple[Candidate, str, Path | None]],
) -> None:
    manifest_csv.parent.mkdir(parents=True, exist_ok=True)

    with manifest_csv.open("w", newline="", encoding="utf-8") as f:
        writer = csv.writer(f)
        writer.writerow([
            "timestamp",
            "script",
            "mode",
            "project_root",
            "kind",
            "original_path",
            "action",
            "archive_path",
            "file_count",
            "dir_count",
            "total_bytes",
            "reason",
        ])

        now = datetime.now().isoformat(timespec="seconds")
        for candidate, action, archive_path in actions:
            writer.writerow([
                now,
                SCRIPT_NAME,
                mode,
                project_root.as_posix(),
                candidate.kind,
                candidate.relpath.as_posix(),
                action,
                "" if archive_path is None else archive_path.as_posix(),
                candidate.file_count,
                candidate.dir_count,
                candidate.total_bytes,
                candidate.reason,
            ])

    total_files = sum(c.file_count for c in candidates)
    total_dirs = sum(c.dir_count for c in candidates)
    total_bytes = sum(c.total_bytes for c in candidates)

    with manifest_txt.open("w", encoding="utf-8") as f:
        f.write(f"{SCRIPT_NAME} manifest\n")
        f.write("=" * 72 + "\n")
        f.write(f"Mode:         {mode}\n")
        f.write(f"Project root: {project_root}\n")
        f.write(f"Items:        {len(candidates)}\n")
        f.write(f"Files:        {total_files}\n")
        f.write(f"Dirs:         {total_dirs}\n")
        f.write(f"Size:         {format_bytes(total_bytes)}\n\n")

        for candidate, action, archive_path in actions:
            f.write(f"- {candidate.relpath.as_posix()}\n")
            f.write(f"  kind:   {candidate.kind}\n")
            f.write(f"  action: {action}\n")
            if archive_path is not None:
                f.write(f"  archive_path: {archive_path.as_posix()}\n")
            f.write(f"  files:  {candidate.file_count}\n")
            f.write(f"  dirs:   {candidate.dir_count}\n")
            f.write(f"  bytes:  {candidate.total_bytes}\n")
            f.write(f"  reason: {candidate.reason}\n\n")


def print_summary(candidates: Sequence[Candidate], *, mode: str) -> None:
    total_files = sum(c.file_count for c in candidates)
    total_dirs = sum(c.dir_count for c in candidates)
    total_bytes = sum(c.total_bytes for c in candidates)

    print(f"Mode:  {mode}")
    print(f"Items: {len(candidates)}")
    print(f"Files: {total_files}")
    print(f"Dirs:  {total_dirs}")
    print(f"Size:  {format_bytes(total_bytes)}")
    print()

    if not candidates:
        print("No cleanup candidates found.")
        return

    for candidate in candidates:
        print(
            f"[{candidate.kind}] {candidate.relpath.as_posix()} "
            f"({candidate.file_count} files, {format_bytes(candidate.total_bytes)})"
        )


def archive_candidates(
    candidates: Sequence[Candidate],
    *,
    project_root: Path,
    archive_root: Path,
) -> tuple[Path, list[tuple[Candidate, str, Path | None]]]:
    timestamp = datetime.now().strftime("%Y%m%d_%H%M%S")
    archive_dir = archive_root / f"cleanup-{timestamp}"
    archive_dir.mkdir(parents=True, exist_ok=False)

    actions: list[tuple[Candidate, str, Path | None]] = []

    for candidate in candidates:
        dest = archive_dir / candidate.relpath
        dest.parent.mkdir(parents=True, exist_ok=True)

        if dest.exists():
            raise FileExistsError(f"Archive destination already exists: {dest}")

        shutil.move(str(candidate.path), str(dest))
        actions.append((candidate, "archived", dest.relative_to(project_root)))

    manifest_csv = archive_dir / "manifest.csv"
    manifest_txt = archive_dir / "manifest.txt"
    write_manifest(
        manifest_csv,
        manifest_txt,
        project_root=project_root,
        mode="archive",
        candidates=candidates,
        actions=actions,
    )

    return archive_dir, actions


def delete_candidates(
    candidates: Sequence[Candidate],
    *,
    project_root: Path,
) -> list[tuple[Candidate, str, Path | None]]:
    actions: list[tuple[Candidate, str, Path | None]] = []

    for candidate in candidates:
        shutil.rmtree(candidate.path)
        actions.append((candidate, "deleted", None))

    timestamp = datetime.now().strftime("%Y%m%d_%H%M%S")
    manifest_dir = project_root / DEFAULT_ARCHIVE_DIRNAME / f"delete-manifest-{timestamp}"
    manifest_dir.mkdir(parents=True, exist_ok=False)

    write_manifest(
        manifest_dir / "manifest.csv",
        manifest_dir / "manifest.txt",
        project_root=project_root,
        mode="delete",
        candidates=candidates,
        actions=actions,
    )

    return actions



def resolve_restore_archive_dir(project_root: Path, archive_dir: Path) -> Path:
    """Resolve an archive directory path for --restore."""
    if archive_dir.is_absolute():
        return archive_dir.resolve()
    return (project_root / archive_dir).resolve()


def read_archive_manifest(archive_dir: Path) -> list[dict[str, str]]:
    """Read manifest.csv from an archive created by --archive."""
    manifest_csv = archive_dir / "manifest.csv"
    if not manifest_csv.is_file():
        raise FileNotFoundError(f"Archive manifest not found: {manifest_csv}")

    with manifest_csv.open("r", newline="", encoding="utf-8") as f:
        reader = csv.DictReader(f)
        rows = list(reader)

    required = {"original_path", "archive_path", "action", "kind"}
    missing = required.difference(reader.fieldnames or [])
    if missing:
        missing_list = ", ".join(sorted(missing))
        raise ValueError(f"Archive manifest is missing required columns: {missing_list}")

    return rows


def restore_archive(
    *,
    project_root: Path,
    archive_dir: Path,
    dry_run: bool,
    overwrite: bool,
) -> int:
    """Restore archived workflow-output directories.

    Default behavior is intentionally conservative: existing targets are skipped.
    With overwrite=True, existing targets are first moved into a restore backup
    directory under _cleanup_archive instead of being deleted outright.
    """
    rows = read_archive_manifest(archive_dir)

    timestamp = datetime.now().strftime("%Y%m%d_%H%M%S")
    restore_backup_dir = (
        project_root
        / DEFAULT_ARCHIVE_DIRNAME
        / f"restore-overwrite-backup-{timestamp}"
    )

    planned: list[tuple[Path, Path, str]] = []
    skipped: list[tuple[Path, str]] = []

    for row in rows:
        if row.get("action") != "archived":
            skipped.append((Path(row.get("original_path", "")), "manifest row is not an archived item"))
            continue

        original_rel = Path(row["original_path"])
        archive_rel_raw = row["archive_path"]

        # Restore source resolution:
        #
        # The archive manifest stores archive_path relative to the original
        # project root, for example:
        #
        #   _cleanup_archive/cleanup-20260618_102452/20990101_ex_99/.../pchip
        #
        # If the user copies the whole archive directory for a restore test, that
        # manifest still points to the original archive. Therefore the selected
        # archive directory must be authoritative. Resolve the source primarily
        # as:
        #
        #   <selected archive dir>/<original_path>
        #
        # and use the manifest archive_path only as a compatibility fallback.
        src = archive_dir / original_rel
        dst = project_root / original_rel

        if not src.exists() and archive_rel_raw:
            archive_rel = Path(archive_rel_raw)
            fallback_src = project_root / archive_rel
            try:
                fallback_src.relative_to(archive_dir)
            except ValueError:
                pass
            else:
                src = fallback_src

        # Basic safety checks.
        try:
            src.relative_to(archive_dir)
        except ValueError:
            skipped.append((original_rel, f"archive source outside selected archive: {src}"))
            continue

        if not src.exists():
            skipped.append((original_rel, f"archive source missing: {src}"))
            continue

        if contains_never_touch_path(src, project_root):
            skipped.append((original_rel, "archive source contains protected paths"))
            continue

        if dst.exists() and not overwrite:
            skipped.append((original_rel, "target exists; skipped without --restore-overwrite"))
            continue

        planned.append((src, dst, row.get("kind", "")))

    print(f"Restore archive: {archive_dir}")
    print(f"Mode: {'restore-dry-run' if dry_run else 'restore'}")
    print(f"Items planned: {len(planned)}")
    print(f"Items skipped: {len(skipped)}")
    print()

    for src, dst, kind in planned:
        print(f"[restore:{kind}] {src.relative_to(project_root).as_posix()} -> {dst.relative_to(project_root).as_posix()}")

    if skipped:
        print()
        print("Skipped:")
        for rel, reason in skipped:
            print(f"[skip] {rel.as_posix()}: {reason}")

    if dry_run:
        print()
        print("Restore dry-run only. No files or directories were modified.")
        return 0

    for src, dst, _kind in planned:
        dst.parent.mkdir(parents=True, exist_ok=True)

        if dst.exists():
            # Non-destructive overwrite: move current target aside first.
            backup_dst = restore_backup_dir / dst.relative_to(project_root)
            backup_dst.parent.mkdir(parents=True, exist_ok=True)
            shutil.move(str(dst), str(backup_dst))

        shutil.move(str(src), str(dst))

    print()
    if planned:
        print("Restore complete.")
    else:
        print("No items were restored.")

    if overwrite and restore_backup_dir.exists():
        print(f"Overwritten existing targets were backed up under: {restore_backup_dir}")

    return 0


def main() -> int:
    args = parse_args()
    project_root = args.project_root.resolve()

    if not project_root.is_dir():
        print(f"[error] project root is not a directory: {project_root}", file=sys.stderr)
        return 2

    if not args.allow_untrusted_root and not looks_like_project_root(project_root):
        print(
            "[error] project root does not look like a PCHIP snapshot "
            "(expected scripts/ and *_ex_* experiment directories).",
            file=sys.stderr,
        )
        print(
            "        Use --project-root <path> or --allow-untrusted-root if this is intentional.",
            file=sys.stderr,
        )
        return 2

    mode = "dry-run"
    if args.archive:
        mode = "archive"
    elif args.delete:
        mode = "delete"
    elif args.restore:
        mode = "restore"

    if args.restore:
        archive_dir = resolve_restore_archive_dir(project_root, args.restore)
        if not archive_dir.is_dir():
            print(f"[error] restore archive is not a directory: {archive_dir}", file=sys.stderr)
            return 2

        return restore_archive(
            project_root=project_root,
            archive_dir=archive_dir,
            dry_run=args.restore_dry_run,
            overwrite=args.restore_overwrite,
        )

    candidates = collect_candidates(
        project_root,
        only=args.only,
        experiments=args.experiments,
        include_galleries=args.include_galleries,
        require_marker=args.require_marker,
        verbose=args.verbose,
    )

    print_summary(candidates, mode=mode)

    if args.dry_run:
        print()
        print("Dry-run only. No files or directories were modified.")
        return 0

    if not candidates:
        return 0

    if args.archive:
        archive_root = resolve_archive_root(project_root, args.archive_root)
        archive_dir, _actions = archive_candidates(
            candidates,
            project_root=project_root,
            archive_root=archive_root,
        )
        print()
        print(f"Archived cleanup candidates under: {archive_dir}")
        print(f"Manifest: {archive_dir / 'manifest.csv'}")
        return 0

    if args.delete:
        delete_candidates(candidates, project_root=project_root)
        print()
        print(
            "Deleted cleanup candidates. A delete manifest was written under "
            f"{project_root / DEFAULT_ARCHIVE_DIRNAME}."
        )
        return 0

    raise AssertionError("unreachable")


if __name__ == "__main__":
    raise SystemExit(main())
